Add missing ontology definition and avoid redefinition from other ontologies.
wiresio/wot-discovery pull request #1
Opened 2022-02-15 16:59 UTC by Murloc6

This PR adds some missing definition into the ontology, but used in the context.
It removes the redefinition of td:Thing.
It defines its proper object properties, which inherit from schema ones and remove the schema properties definition.

2022-02-15 17:02 UTC, Murloc6 commented
ping @ethieblin if you want to review this.

2022-02-16 11:15 UTC, ethieblin requested changes

2022-02-16 11:15 UTC, ethieblin commented on context/discovery-ontology.ttl
> +discovery:members rdf:type owl:ObjectProperty;
according to the change in the context, it would be discovery:hasCollectionMember https://github.com/wiresio/wot-discovery/blob/f326e8de44a4f0fe06cda269eb497437f708f599/context/discovery-context.jsonld#L25

2022-02-16 11:15 UTC, ethieblin commented on context/discovery-ontology.ttl
> +    rdfs:range discovery:Thing;
td:Thing ?

2022-02-16 11:15 UTC, ethieblin commented on context/discovery-ontology.ttl
> +	rdfs:label "total"@en .
total number of things in the collection ? (comment could be a bit more expressive)

2022-02-16 11:15 UTC, ethieblin commented on context/discovery-ontology.ttl
>  	rdfs:domain discovery:RegitrationInformation ;
Not in your commit, but there is a typo in the ontology discovery:RegitrationInformation --> "RegistrationInformation"
This typo is not in the context

2022-02-16 11:15 UTC, ethieblin commented on context/discovery-ontology.ttl
> +discovery:total rdf:type owl:DatatypeProperty ;
it seems that the URI for the "total" term is discovery:contains https://github.com/wiresio/wot-discovery/blob/f326e8de44a4f0fe06cda269eb497437f708f599/context/discovery-context.jsonld#L21

2022-02-16 11:15 UTC, ethieblin commented on context/discovery-ontology.ttl
> +	rdfs:subClassOf td:Thing .
Are we sure that a ThingCollection is a subClass of td:Thing ? I'm not against it, but I'm not sure what we are reprensenting with this concept.

2022-02-18 08:42 UTC, Murloc6 commented
Thank you @ethieblin for the accurate review.
I fixed all your recommendations here.
By the way, maybe @wiresio you have a clue if we should define a discovery:ThingCollection as a td:Thing or not? I guess this is not a td:Thing, but not 100% sure.

Another question that is pretty important, the `RegistrationInformation` (dateCreated, dateModified, expires, ttl and retrieve) should probably be present in the Thing ontology, because there is no link with the discovery. Or am I missing something ?

2022-02-19 17:39 UTC, merged